chore: POSIX 호환 shell을 사용하도록 지정 & tab size 4 적용
시스템 간 호환성을 위해 bash shell 대신 POSIX 호환 shell을 사용하도록 지정했다.
다른 파일들과의 통일성을 위해 tab size를 2에서 4로 변경해 적용했다.

diff --git a/backend/.husky/pre-commit b/backend/.husky/pre-commit
--- a/backend/.husky/pre-commit
+++ b/backend/.husky/pre-commit
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 NC='\033[0m'
 GREEN='\033[0;32m'
@@ -18,14 +18,14 @@ echo -e "${GREEN}[INFO]${NC} 현재 branch name: ${BLUE}${current_branch}${NC}"
 
 # Check if the current branch name follows project's naming convention
 if [[ ! $current_branch =~ ^(frontend|backend|infra)\/DANG-[1-9][0-9]*$ ]]; then
-  echo -e "${RED}[ERROR]${NC} 현재 branch name의 형식이 맞지 않습니다. (ex. frontend/DANG-1, backend/DANG-26, infra/DANG-72)"
-  exit 1
+	echo -e "${RED}[ERROR]${NC} 현재 branch name의 형식이 맞지 않습니다. (ex. frontend/DANG-1, backend/DANG-26, infra/DANG-72)"
+	exit 1
 fi
 
 # Check if the current branch starts with "backend"
 if [[ $current_branch == frontend* ]]; then
-  echo -e "${YELLOW}[WARNING]${NC} frontend 폴더에서 작업하셨나요? 현재 실행 중인 스크립트가 backend 폴더에 위치하고 있습니다."
-  echo -e "${YELLOW}[WARNING]${NC} frontend 설정으로 스크립트를 실행하려면 ${PINK}frontend 폴더에서${NC} ${MAGENTA}npm run prepare${NC}를 실행 한 뒤 다시 ${MAGENTA}git commit${NC}을 시도하세요."
+	echo -e "${YELLOW}[WARNING]${NC} frontend 폴더에서 작업하셨나요? 현재 실행 중인 스크립트가 backend 폴더에 위치하고 있습니다."
+	echo -e "${YELLOW}[WARNING]${NC} frontend 설정으로 스크립트를 실행하려면 ${PINK}frontend 폴더에서${NC} ${MAGENTA}npm run prepare${NC}를 실행 한 뒤 다시 ${MAGENTA}git commit${NC}을 시도하세요."
 fi
 
 cd backend
